language: php
php:
    - "5.4"
    - "5.5"
    - "5.6"
before_install:
    - php /home/travis/.phpenv/version/5.4.25/bin/composer.phar self-updated
before_script:
    - composer install
script: phpunit --configuration phpunit.xml --coverage-text